dataset: misato # pdbbind
name: none
mode: all
test_set: /path/to/dataset/MISATO/test_subset20.jsonl # /path/to/dataset/PDBBind_All/test_clean_noh.jsonl
ckpt: /path/to/checkpoint
refiner: null
save_dir: null
inf_step: 100
sde_step: 10
batch_size: 1
gpu: 0
