data:
  dataset: uni                # default dataset type, DO NOT CHANGE
  same_origin: false          # whether the selected data in a mini-batch are of the same molecule, DO NOT CHANGE
  complexity: "n"             # pre-defined computational complexity w.r.t. the number of atoms
  ubound_per_batch: 2_000     # upper bound of the complexity of each mini-batch, depends on CUDA memory
  max_batches: 60_000         # upper bound of mini-batches in an epoch for each dataset
  path:
    ### pretrain
    ### NOTE THAT raw data of each dataset should be first pre-processed by `data/{dataset_name}_dataset.py`, which yields `train_block` and `valid_block` directories
    pdb_train: dataset/PDB/train_block  # training split of the dataset
    pdb_valid: dataset/PDB/valid_block  # validation split of the dataset
    ### md
    # mdcath_train: dataset/mdCATH/train_block
    # mdcath_valid: dataset/mdCATH/val_block

training:
  lr: 0.0001                            # learning rate
  loss_type: null                       # default: null, DO NOT CHANGE
  warmup: 1_000                         # warm-up steps
  max_epoch: 200                        # maximum training epochs
  grad_clip: 1.0                        # gradient clip, default: 1.0
  batch_size: 4                         # batch size, NOTE THAT you should only specify batch_size=number of GPUs, since mini-batches will be wrapped to one single batch before sending to DataLoader
  patience: 8                           # patience for early stop, based on validation loss
  save_topk: 10                         # number of saved checkpoints
  shuffle: true                         # whether to shuffle batches during each epoch
  num_workers: 8                        # number of CPU workers, default: 8
  save_dir: ckpt/pretrain               # directories for saving checkpoints
  wrapper:
    ema:
      update_after_step: 1_000_000      # the training step at which EMA is applied, default: 1_000_000

model:
  ref: null                             # specify the reference model checkpoint, ONLY FOR adjoint matching
  ckpt: null                            # specify the checkpoint to be loaded, default: null (training from scratch)
  model_type: md                        # specify the training stages: pretraining ('pretrain'), fine-tuning on paired trajectory data ('md'), and adjoint matching ('adj')
  hidden_dim: 256                       # hidden dimensions, default: 256
  ffn_dim: 512                          # FFN dimensions, default: 512
  rbf_dim: 32                           # RBF dimensions, default: 32
  heads: 8                              # the number of attention heads, default: 8
  layers: 8                             # the number of decoder layers, default: 8
  cutoff_lower: 0.0                     # lower bound of RBF cutoff, default: 0.0 Angstrom
  cutoff_upper: 10.0                    # upper bound of RBF cutoff, default: 10.0 Angstrom
  cutoff_H: 3.5                         # NOT USED
  k_neighbors: 32                       # the number of neighbors for KNN graph construction, default: 32
  coord_prior_var: 0.5                  # variational noise scale, default: sqrt(0.5)
  sigma: 0.2                            # SDE noise scale, default: 0.2
  additional_noise_scale: 0.2           # perturbation strength, default: 0.2
  kl_weight: 0.8                        # KL loss weight, default: 0.8
  re_weight: 1.0                        # ABM loss weight, default: 1.0
  reward_weight: 100.0                  # reward weight for adjoint matching, default: 100
  rl_sde_step: 10                       # discrete SDE step for adjoint matching, default: 10
  using_ode: false                      # whether to use ODE to model the bridge, default: false
  backbone: torchmdnet                  # backbone module type, default: torchmdnet, DO NOT CHANGE