from rdkit import Chem
from rdkit.Chem import AllChem
from Bio.PDB import PDBParser, MMCIFParser, PDBIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio import SeqIO
from Bio.SeqUtils import seq1
from e3nn.o3 import rand_matrix
from pdbfixer import PDBFixer
from openmm.app import PDBFile
from openmm.vec3 import Vec3
import mdtraj as md
from argparse import ArgumentParser
from tqdm import tqdm
import os
import subprocess
import json
import numpy as np
from openbabel import pybel

from utils.geometry import kabsch_numpy
from utils.docking_vina import VinaDockingTask
from post_process import write_coord_to_sdf


def load_file(fpath):
    with open(fpath, 'r') as fin:
        lines = fin.read().strip().split('\n')
    items = [json.loads(s) for s in lines]
    return items


def apo_ligand(input_sdf, output_sdf):
    mol = Chem.SDMolSupplier(input_sdf, removeHs=False)[0]
    # mol = Chem.AddHs(mol)
    writer = Chem.SDWriter(output_sdf)
    # status = AllChem.EmbedMolecule(mol, AllChem.ETKDGv2())
    mp = AllChem.MMFFGetMoleculeProperties(mol, mmffVariant='MMFF94')
    ff = AllChem.MMFFGetMoleculeForceField(mol, mp)
    ff.Minimize(maxIts=500)
    writer.write(mol)
    writer.close()


def pdb_to_fasta(pdb_file, fasta_file):
    traj = md.load(pdb_file)
    records = []

    exclude_residues = {'HOH', 'NA', 'MG', 'CA', 'CL'}

    for chain in traj.topology.chains:
        if chain.chain_id == ' ':
            continue
        sequence = ''
        for residue in chain.residues:
            res_name = residue.name.strip()
            if res_name not in exclude_residues:
                sequence += seq1(res_name)
        record = SeqRecord(Seq(sequence), id=f"{chain.chain_id}|protein", description="")
        records.append(record)
    
    SeqIO.write(records, fasta_file, "fasta")


def apo_protein(input_pdb, output_pdb):
    input_base, input_file = os.path.split(input_pdb)
    pdb, name = input_file[:4], input_file[:-4]
    fasta = os.path.join(input_base, f"{name}.fasta")
    pdb_to_fasta(input_pdb, fasta)
    script = f"boltz predict {fasta} --use_msa_server --cache /path/to/boltz"
    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = "0"
    subprocess.run(script.split(), check=True, env=env)
    pred_cif = os.path.join(os.path.abspath('.'), f'boltz_results_{name}', 'predictions', name, f'{name}_model_0.cif')
    parser = MMCIFParser()
    structure = parser.get_structure("anony", pred_cif)
    io = PDBIO()
    io.set_structure(structure)
    io.save(output_pdb)
    boltz_results = os.path.join(os.path.abspath('.'), f'boltz_results_{name}')
    subprocess.run(['mv', boltz_results, os.path.join(os.path.split(output_pdb)[0])], check=True)


def parse():
    parser = ArgumentParser(description='simulation')
    parser.add_argument('--summary', type=str, required=True, help='Path to summary file')
    return parser.parse_args()


if __name__ == "__main__":
    args = parse()
    items = load_file(args.summary)
    for item in tqdm(items):
        pdb, ligand_path, protein_path = item["pdb"], item["ligand_path"], item["protein_path"]
        save_dir = os.path.split(ligand_path)[0]
        # print(f"[+] Start predicting apo structures: {pdb}.")
        apo_ligand_path = os.path.join(save_dir, "apo_ligand.sdf")
        apo_protein_path = os.path.join(save_dir, "apo_protein.pdb")
        boltz_result_path = os.path.join(save_dir, f'boltz_results_{pdb}_protein')
        if pdb != '':
            continue
        try:
            apo_ligand(ligand_path, apo_ligand_path)
        except Exception as e:
            print(f"Generating apo structure of ligand of PDB {pdb} failed: {e}.")
            # subprocess.run(['cp', ligand_path, apo_ligand_path], check=True)
        try:
            subprocess.run(['rm', '-rf', boltz_result_path], check=True)
            apo_protein(protein_path, apo_protein_path)
        except Exception as e:
            print(f"Generating apo structure of receptor of PDB {pdb} failed: {e}.")
            subprocess.run(['cp', protein_path, apo_protein_path], check=True)
    
    # generating arbitrary apo structures
    ligand_rmsd_res = []
    for item in tqdm(items):
        pdb, ligand_path, protein_path, pocket_idx = item["pdb"], item["ref_ligand_path"], item["ref_protein_path"], item["pocket_idx"]
        save_dir = os.path.split(ligand_path)[0]
        apo_ligand_path = os.path.join(save_dir, "apo_ligand.sdf")
        apo_protein_path = os.path.join(save_dir, "apo_protein.pdb")        # generated by Boltz-1
        if not os.path.exists(apo_protein_path):
            apo_protein_path = os.path.join(save_dir, "apo_protein.cif")    # generated by Alphafold-3
        
        # add missing atoms
        apo_protein_fixed_path = os.path.join(save_dir, "apo_protein_fixed.pdb")
        holo_protein_fixed_path = os.path.join(save_dir, "holo_protein_fixed.pdb")
        apo_fixer = PDBFixer(apo_protein_path)
        apo_fixer.findMissingResidues()
        apo_fixer.findMissingAtoms()
        apo_fixer.addMissingAtoms()
        apo_fixer.addMissingHydrogens(7.0)
        # apo_fixer.removeHeterogens(False)
        with open(apo_protein_fixed_path, 'w') as f:
            PDBFile.writeFile(apo_fixer.topology, apo_fixer.positions, f)
        holo_fixer = PDBFixer(protein_path)
        holo_fixer.findMissingResidues()
        holo_fixer.findMissingAtoms()
        holo_fixer.addMissingAtoms()
        holo_fixer.addMissingHydrogens(7.0)
        # holo_fixer.removeHeterogens(False)
        with open(holo_protein_fixed_path, 'w') as f:
            PDBFile.writeFile(holo_fixer.topology, holo_fixer.positions, f)
        
        # align apo structure to holo - protein
        holo_protein_traj = md.load(holo_protein_fixed_path)
        apo_protein_traj = md.load(apo_protein_fixed_path)
        pocket_residues = [holo_protein_traj.topology.residue(r) for r in pocket_idx]
        pocket_bb_idx = np.concatenate([[a.index for a in res.atoms if (a.name == 'CA' or a.name == 'C' or a.name == 'N')] for res in pocket_residues], dtype=np.compat.long)
        holo_bb_pos = holo_protein_traj.xyz[0][pocket_bb_idx]
        apo_bb_pos = apo_protein_traj.xyz[0][pocket_bb_idx]
        # kabsch alignemnt
        _, Rp, tp = kabsch_numpy(apo_bb_pos, holo_bb_pos)
        apo_protein_pos = apo_protein_traj.xyz[0] @ Rp + tp
        md.Trajectory(
            apo_protein_pos,
            apo_protein_traj.topology
        ).save_pdb(os.path.join(save_dir, "apo_protein_aligned.pdb"))

        # align apo structure to holo - ligand
        holo_ligand_suppl = Chem.SDMolSupplier(ligand_path, removeHs=False, sanitize=False)[0]
        apo_ligand_suppl = Chem.SDMolSupplier(apo_ligand_path, removeHs=False, sanitize=False)[0]
        assert holo_ligand_suppl.GetNumAtoms() == apo_ligand_suppl.GetNumAtoms(), f'atom numbers of holo and apo structure of PDB {pdb} did not match.'
        Nl = holo_ligand_suppl.GetNumAtoms()
        holo_ligand_conf = holo_ligand_suppl.GetConformer()
        apo_ligand_conf = apo_ligand_suppl.GetConformer()
        holo_ligand_pos = holo_ligand_conf.GetPositions().astype(float)
        apo_ligand_pos = apo_ligand_conf.GetPositions().astype(float)
        apo_ligand_pos_aligned, _, _ = kabsch_numpy(apo_ligand_pos, holo_ligand_pos)
        write_coord_to_sdf(apo_ligand_suppl, apo_ligand_pos_aligned.astype(float), os.path.join(save_dir, "apo_ligand_aligned.sdf"))

        mol = Chem.SDMolSupplier(os.path.join(save_dir, "apo_ligand_aligned.sdf"), removeHs=False, sanitize=False)[0]
        vina_task = VinaDockingTask.from_generated_mol(mol, protein_path=os.path.join(save_dir, "apo_protein_aligned.pdb"))
        dock_res = vina_task.run(mode='dock', exhaustiveness=32)[0]

        output_pdbqt = os.path.join(save_dir, "apo_ligand_docked.pdbqt")
        with open(output_pdbqt, 'w') as f:
            f.write(dock_res["pose"])
        pose = list(pybel.readfile('pdbqt', output_pdbqt))[0]
        pose.write('sdf', os.path.join(save_dir, 'apo_ligand_docked.sdf'), overwrite=True)
